DjangoSocialMedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Posts.urls')),
    path('profile/', include('Profile.urls')),
    path('account/', include('Login.urls')),
    path('messages/', include('Messages.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Login/urls.py
from django.urls import path
from . import views


app_name = 'account'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile-setup/', views.setup_profile, name='setup_profile'),
]

Messages/urls.py
from django.urls import path
from . import views



app_name = 'messages'

urlpatterns = [
    path('', views.deport, name='deport'),
    path('<username>/', views.inbox, name='inbox'),
    path('send-message/<pk>/', views.send_message, name='send_message'),
    path('send-picture/<pk>/', views.send_picture, name='send_picture'),
    ]

Posts/urls.py
from django.urls import path
from .views import CreatePost, DeletePost, EditComment, EditPost, ViewPost, comment_like, comment_unlike, delete_comment, feed, post_like, post_unlike, share, share_list, write_comment


app_name = 'post'

urlpatterns = [
    path('', feed, name='feed'),
    path('post/', CreatePost.as_view(), name='create_post'),
    path('post/<pk>/', ViewPost.as_view(), name='single_post'),
    path('edit-post/<pk>/', EditPost.as_view(), name='edit_post'),
    path('delete-post/<pk>/', DeletePost.as_view(), name='delete_post'),
    path('like-post/<int:pk>/', post_like, name='post_like'),
    path('unlike-post/<int:pk>/', post_unlike, name='post_unlike'),
    path('comment/<int:pk>/', write_comment, name='comment'),
    path('edit-comment/<int:pk>/', EditComment.as_view(), name='edit_comment'),
    path('delete-comment/<int:pk>/', delete_comment, name='delete_comment'),
    path('like-comment/<int:pk>/', comment_like, name='comment_like'),
    path('unlike-comment/<int:pk>/', comment_unlike, name='comment_unlike'),
    path('share-post/<pk>/', share_list, name='share_list'),
    path('share/<pk>/', share, name='share'),
]

Profile/urls.py
from django.urls import path
from . import views


app_name = 'profile'

urlpatterns = [
    path('', views.profile, name='profile'),
    path('change-password/', views.change_pass, name='change_pass'),
    path('update-user-info/', views.update_profile, name='update_user'),
    path('<pk>/', views.OtherUserProfile.as_view(), name='user_profile'),
    path('change-profile-picture/<pk>/', views.UpdatePfp.as_view(), name='update_pfp'),
    path('follow/<int:pk>/', views.follow, name='follow'),
    path('unfollow/<int:pk>/', views.unfollow, name='unfollow'),
    path('check-notification/<int:pk>/', views.check_notification, name='check_notification'),
    path('followers/<int:pk>/', views.follower_list, name='followers'),
    path('following/<int:pk>/', views.following_list, name='following'),
    path('post-likes/<int:pk>/', views.post_likers, name='post_likers'),
    path('comment-likes/<int:pk>/', views.comment_likers, name='comment_likers'),
]

Profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from .tasks import new_follow_notify

# Create your models here.

class Follow(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower')
    date_followed = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.follower.username} follows {self.following.username}'

    def save(self, *args, **kwargs):
        response = super().save(*args, **kwargs)
        new_follow_notify.delay(self.following.pk, self.follower.pk, self.pk)

        return response


class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notifications')
    notifier = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notifier')
    notification = models.CharField(max_length=400)
    post = models.ForeignKey('Posts.Post', on_delete=models.CASCADE, blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)
    unread = models.BooleanField(default=True)
    
    model = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()

    object = GenericForeignKey('model', 'object_id')

    follow = models.BooleanField(default=False)
    post_like = models.BooleanField(default=False)
    comment = models.BooleanField(default=False)
    comment_like = models.BooleanField(default=False)


    def __str__(self):
        return f'{self.notifier} {self.notification}.'

    class Meta:
        ordering = ('-date',)

Profile/forms.py
from django import forms
from Login.models import User, UserProfile
from phonenumber_field.formfields import PhoneNumberField


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email',)

class UserProfileUpdateForm(forms.ModelForm):
    phone_number = PhoneNumberField(required=False)
    dob = forms.DateField(required=False, widget=forms.TextInput(attrs={'type':'date'}))
    class Meta:
        model = UserProfile
        fields = ('bio', 'dob', 'country', 'phone_number', 'facebook_profile', 'insta_profile')

Profile/views.py
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import Http404, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views.generic import UpdateView, DetailView
from Login.models import UserProfile, User
from .forms import UserUpdateForm, UserProfileUpdateForm
from django.urls import reverse
from .models import Follow, Notification
from Posts.models import CommentLike, Post, Comment, PostLike

# Create your views here.
        
@login_required
def profile(req):
    return render(req, 'Profile/profile.html', context={})

@login_required
def update_profile(req):
    form1 = UserUpdateForm(instance=req.user)
    form2 = UserProfileUpdateForm(instance=req.user.profile)
    if req.method == 'POST':
        form1 = UserUpdateForm(data=req.POST, instance=req.user)
        form2 = UserProfileUpdateForm(data=req.POST, instance=req.user.profile)
        if form1.is_valid() and form2.is_valid():
            form1.save()
            form2.save()
            return redirect('profile:profile')

    return render(req, 'Profile/user_update.html', context={'test':'working','form1':form1,'form2':form2})

class UpdatePfp(LoginRequiredMixin, UpdateView):
    model = UserProfile
    fields = ('set_pro_pic',)
    template_name = 'Profile/pf_change.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['propic'] = True

        return context
    
    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.user.pk != self.request.user.pk:
            raise Http404
        return super(UpdatePfp, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('profile:profile')


@login_required
def change_pass(req):
    user = req.user
    form = PasswordChangeForm(user)

    if req.method == 'POST':
        form = PasswordChangeForm(user, data=req.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(req, user)
            return redirect('profile:profile')

    return render(req, 'Profile/pf_change.html', context={'form':form})


@login_required
def check_notification(req, pk):
    notification = Notification.objects.get(pk=pk)
    notification.unread = False
    notification.save()
    if notification.post:
        return redirect('post:single_post', pk=notification.post.pk)
    else:
        return redirect('profile:user_profile', pk=notification.notifier.pk)


class OtherUserProfile(DetailView):
    model = User
    template_name = 'Profile/profile.html'
    context_object_name = 'other_user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['other'] = True

        return context

    def dispatch(self, request, *args, **kwargs):
        if self.get_object() == request.user:
            return redirect('profile:profile')

        return super().dispatch(request, *args, **kwargs)


@login_required
def follow(req, pk):
    following = User.objects.get(pk=pk)
    follower = req.user
    if Follow.objects.filter(follower=follower, following=following):
        raise Http404

    new_follow = Follow(follower=follower, following=following)
    new_follow.save()

    return HttpResponseRedirect(req.META.get('HTTP_REFERER'))


@login_required
def unfollow(req, pk):
    following = User.objects.get(pk=pk)
    follower = req.user
    new_follow = Follow.objects.get(follower=follower, following=following)
    new_follow.delete()

    return HttpResponseRedirect(req.META.get('HTTP_REFERER'))


def follower_list(req, pk):
    current_user = User.objects.get(pk=pk)
    follow = Follow.objects.filter(follower=req.user).values_list('following', flat=True)
    
    return render(req, 'Profile/users_list.html', context={'current_user':current_user, 'followers':True, 'follow':follow})


def following_list(req, pk):
    current_user = User.objects.get(pk=pk)
    follow = Follow.objects.filter(follower=req.user).values_list('following', flat=True)
    
    return render(req, 'Profile/users_list.html', context={'current_user':current_user, 'following':True, 'follow':follow})


def post_likers(req, pk):
    post = Post.objects.get(pk=pk)
    likes = PostLike.objects.filter(post=post)
    follow = Follow.objects.filter(follower=req.user).values_list('following', flat=True)
    
    return render(req, 'Profile/users_list.html', context={'likes':likes, 'like_list':True, 'follow':follow})


def comment_likers(req, pk):
    comment = Comment.objects.get(pk=pk)
    likes = CommentLike.objects.filter(comment=comment)
    follow = Follow.objects.filter(follower=req.user).values_list('following', flat=True)

    return render(req, 'Profile/users_list.html', context={'likes':likes, 'like_list':True, 'follow':follow})

templates/Profile/pf_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}

    <center>
        <div class="col-sm-4">
            {% if propic %}
            <h4>Currently:</h4>
            <img src="/media/{{user.profile.set_pro_pic}}" alt="" width="80%">
            {% endif %}
            <form method="POST" enctype="multipart/form-data">
                {{ form|crispy }}
                {% csrf_token %}

                <button type="submit" class="btn btn-danger" style="width: 100%; margin-top: 20px;">{% if propic %}Update Profile Picture{% else %}Change Password{% endif %}</button>
            </form>
        </div>
    </center>

{% endblock %}

templates/Profile/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load custom_filter %}

{% block body %}

    {% if other %}

    <div class="row">
        <div class="col-sm-4">
            <center>
                <img class="rounded-circle" src="/media/{{ other_user.profile.pro_pic }}" width="150px" height="150px">
            </center>
        </div>
        <div class="col-sm-8">
            <h3 style="font-weight: 300; display: inline-block; margin-right: 40px;">{{other_user.username}}</h3>
            
            {% if user.pk in other_user.follower.all|as_list %}
            <a href="{% url 'profile:unfollow' pk=other_user.pk %}" class="btn btn-primary" style="margin-top: -8px;">Unfollow</a>
            {% else %}
            <a href="{% url 'profile:follow' pk=other_user.pk %}" class="btn btn-primary" style="margin-top: -8px;">Follow</a>
            {% endif %}
            <a href="{% url 'messages:inbox' username=other_user.username %}" class="btn btn-light" style="border: 1px solid #000; margin-top: -8px; margin-left: 40px;">Message</a>
            
            <br>
            <br>
            <h4>
                {{other_user.posts.count}} <span style="font-weight: 300;">Posts</span> &nbsp &nbsp 
                <a style="text-decoration: none; color: #000;" href="{% url 'profile:followers' pk=other_user.pk %}">{{other_user.follower.count}} <span style="font-weight: 300;">Followers</span></a> &nbsp &nbsp 
                <a style="text-decoration: none; color: #000;" href="{% url 'profile:following' pk=other_user.pk %}">{{other_user.following.count}} <span style="font-weight: 300;">Following</span></a>
            </h4>
            <br>
            <h5>{{other_user.first_name}} {{other_user.last_name}}</h5>
            <p>{{other_user.profile.bio|linebreaks}}</p>
        </div>
    </div>
    <br>
    <br>
    <hr>
    <br>
    <br>
    <div class="row">
    {% for post in other_user.posts.all %}
        <div class="col-sm-4">
            <a href="{% url 'post:single_post' pk=post.pk %}"><img src="/media/{{ post.image }}" alt="" width="100%"></a>
        </div>
    {% endfor %}
    </div>

    {% else %}

    <div class="row">
        <div class="col-sm-4">
            <center>
                <img class="rounded-circle" src="/media/{{ user.profile.pro_pic }}" width="150px" height="150px"><br>
                <a href="{% url 'profile:update_pfp' pk=user.profile.pk %}" class="btn btn-primary btn-sm" style="margin-top: 40px; width: 60%;">Change Profile Picture</a>
            </center>
        </div>
        <div class="col-sm-8">
            <h3 style="font-weight: 300; display: inline-block; margin-right: 40px;">{{user.username}}</h3>
            <a href="{% url 'profile:update_user' %}" class="btn btn-sm btn-light" style="margin-top: -13px; margin-right: 40px;">Edit Profile</a>
            <br>
            <br>

            <h4>{{user.posts.count}} 
                <span style="font-weight: 300;">Posts</span> &nbsp &nbsp
                <a style="text-decoration: none; color: #000;" href="{% url 'profile:followers' pk=user.pk %}">{{user.follower.count}} <span style="font-weight: 300;">Followers</span> &nbsp &nbsp</a>
                <a style="text-decoration: none; color: #000;" href="{% url 'profile:following' pk=user.pk %}">{{user.following.count}} <span style="font-weight: 300;">Following</span></a>
            </h4>

            <br>
            <h5>{{user.first_name}} {{user.last_name}}</h5>
            <p>{{user.profile.bio|linebreaks}}</p>
        </div>
    </div>
    <br>
    <br>
    <hr>
    <br>
    <br>
    <div class="row">
    {% for post in user.posts.all %}
        <div class="col-sm-4">
            <a href="{% url 'post:single_post' pk=post.pk %}"><img src="/media/{{ post.image }}" alt="" width="100%"></a>
        </div>
    {% endfor %}
    </div>

    {% endif %}

{% endblock %}

templates/Profile/user_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}

    <center>
        <div class="col-sm-4">
            <form method="POST" enctype="multipart/form-data">
                {{ form1|crispy }}
                {{ form2|crispy }}
                {% csrf_token %}

                <button type="submit" class="btn btn-danger" style="width: 100%;">Update Profile</button>
            </form>
        </div>
    </center>

{% endblock %}

templates/Profile/users_list.html
{% extends 'base.html' %}
{% load custom_filter %}

{% block body %}

    <div class="row">
        {% if followers %}
        <div class="offset-sm-4">
            <h2>Followers</h2>
        </div>
        {% for f in current_user.follower.all %}
        <div class="col-sm-3 offset-sm-4">
            <a href="{% url 'profile:user_profile' pk=f.follower.pk %}" style="font-size: 18px; text-decoration: none; color: #000; display: inline-block;">{{f.follower}}</a>
        </div>
        <div class="col-sm-2">
            {% if user != f.follower %}
            {% if f.follower.pk in follow %}
            <a href="{% url 'profile:unfollow' pk=f.follower.pk %}" class="btn btn-sm btn-primary" style="margin-top: -8px;">Unfollow</a>
            {% else %}
            <a href="{% url 'profile:follow' pk=f.follower.pk %}" class="btn btn-sm btn-primary" style="margin-top: -8px;">Follow</a>
            {% endif %}
            {% endif %}
        </div>
        <br>
        <br>
        {% endfor %}

        {% elif following %}
        <div class="offset-sm-4">
            <h2>Following</h2>
        </div>
        {% for f in current_user.following.all %}
        <div class="col-sm-3 offset-sm-4">
            <a href="{% url 'profile:user_profile' pk=f.following.pk %}" style="font-size: 18px; text-decoration: none; color: #000; display: inline-block;">{{f.following}}</a>
        </div>
        <div class="col-sm-2">
            {% if user != f.following %}
            {% if f.following.pk in follow %}
            <a href="{% url 'profile:unfollow' pk=f.following.pk %}" class="btn btn-primary btn-sm" style="margin-top: -8px;">Unfollow</a>
            {% else %}
            <a href="{% url 'profile:follow' pk=f.following.pk %}" class="btn btn-primary btn-sm" style="margin-top: -8px;">Follow</a>
            {% endif %}
            {% endif %}
        </div>
        <br>
        <br>
        {% endfor %}
        
        {% elif like_list %}
        <div class="offset-sm-4">
            <h2>Likes</h2>
        </div>
        {% for like in likes %}
        <div class="col-sm-3 offset-sm-4">
            <a href="{% url 'profile:user_profile' pk=like.liker.pk %}" style="font-size: 18px; text-decoration: none; color: #000; display: inline-block;">{{like.liker}}</a>
        </div>
        <div class="col-sm-2">
            {% if user != like.liker %}
            {% if like.liker.pk in follow %}
            <a href="{% url 'profile:unfollow' pk=like.liker.pk %}" class="btn btn-primary btn-sm" style="margin-top: -8px;">Unfollow</a>
            {% else %}
            <a href="{% url 'profile:follow' pk=like.liker.pk %}" class="btn btn-primary btn-sm" style="margin-top: -8px;">Follow</a>
            {% endif %}
            {% endif %}
        </div>
        <br>
        <br>
        {% endfor %}
        
        {% endif %}
    </div>

{% endblock %}