DjangoSocialMedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Posts.urls')),
    path('profile/', include('Profile.urls')),
    path('account/', include('Login.urls')),
    path('messages/', include('Messages.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Login/urls.py
from django.urls import path
from . import views


app_name = 'account'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile-setup/', views.setup_profile, name='setup_profile'),
]

Posts/urls.py
from django.urls import path
from .views import CreatePost, DeletePost, EditComment, EditPost, ViewPost, comment_like, comment_unlike, delete_comment, feed, post_like, post_unlike, share, share_list, write_comment


app_name = 'post'

urlpatterns = [
    path('', feed, name='feed'),
    path('post/', CreatePost.as_view(), name='create_post'),
    path('post/<pk>/', ViewPost.as_view(), name='single_post'),
    path('edit-post/<pk>/', EditPost.as_view(), name='edit_post'),
    path('delete-post/<pk>/', DeletePost.as_view(), name='delete_post'),
    path('like-post/<int:pk>/', post_like, name='post_like'),
    path('unlike-post/<int:pk>/', post_unlike, name='post_unlike'),
    path('comment/<int:pk>/', write_comment, name='comment'),
    path('edit-comment/<int:pk>/', EditComment.as_view(), name='edit_comment'),
    path('delete-comment/<int:pk>/', delete_comment, name='delete_comment'),
    path('like-comment/<int:pk>/', comment_like, name='comment_like'),
    path('unlike-comment/<int:pk>/', comment_unlike, name='comment_unlike'),
    path('share-post/<pk>/', share_list, name='share_list'),
    path('share/<pk>/', share, name='share'),
]

Profile/urls.py
from django.urls import path
from . import views


app_name = 'profile'

urlpatterns = [
    path('', views.profile, name='profile'),
    path('change-password/', views.change_pass, name='change_pass'),
    path('update-user-info/', views.update_profile, name='update_user'),
    path('<pk>/', views.OtherUserProfile.as_view(), name='user_profile'),
    path('change-profile-picture/<pk>/', views.UpdatePfp.as_view(), name='update_pfp'),
    path('follow/<int:pk>/', views.follow, name='follow'),
    path('unfollow/<int:pk>/', views.unfollow, name='unfollow'),
    path('check-notification/<int:pk>/', views.check_notification, name='check_notification'),
    path('followers/<int:pk>/', views.follower_list, name='followers'),
    path('following/<int:pk>/', views.following_list, name='following'),
    path('post-likes/<int:pk>/', views.post_likers, name='post_likers'),
    path('comment-likes/<int:pk>/', views.comment_likers, name='comment_likers'),
]

Posts/models.py
from django.db import models
from django.contrib.auth.models import User
from Profile.models import Notification
from .tasks import comment_notify, post_like_notify, comment_like_notify

# Create your models here.



class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    image = models.ImageField(upload_to='post_images')
    caption = models.CharField(max_length=2000, verbose_name='Write a Captioin', blank=True)
    post_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ('-post_date',)



class PostLike(models.Model):
    liker = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts_liked')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='likes')
    like_date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f'{self.liker} likes {self.post}'


    def save(self, *args, **kwargs):
        response = super().save(*args, **kwargs)
        
        if self.post.author != self.liker:
            post_like_notify.delay(self.post.author.pk, self.liker.pk, self.post.pk, self.pk)

        return response
    

    class Meta:
        ordering = ('-like_date',)



class Comment(models.Model):
    comment = models.TextField(verbose_name='Write a comment..', max_length=1000, default='')
    commentor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    comment_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f'{self.commentor} commented on {self.post}'


    def save(self, *args, **kwargs):
        response = super().save(*args, **kwargs)

        if self.post.author != self.commentor:
            comment_notify.delay(self.post.author.pk, self.commentor.pk, self.post.pk, self.pk)

        return response
    

    class Meta:
        ordering = ('-comment_date',)



class CommentLike(models.Model):
    liker = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments_liked')
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='likes')
    like_date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f'{self.liker} likes {self.comment}'


    def save(self, *args, **kwargs):
        response = super().save(*args, **kwargs)
        
        if self.comment.commentor != self.liker:
            comment_like_notify.delay(self.comment.commentor.pk, self.liker.pk, self.comment.post.pk, self.comment.pk, self.pk)
        
        return response


    class Meta:
        ordering = ('-like_date',)



class Share(models.Model):
    sharer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='shares')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='shared')
    caption = models.CharField(max_length=400, blank=True)
    share_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f'{self.sharer} shared {self.post}'


    class Meta:
        ordering = ('-share_date',)

Posts/views.py
from django.contrib.auth.models import User
from django.db.models.expressions import F
from Profile.models import Follow
from django.http.response import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls.base import reverse
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .models import Comment, CommentLike, Post, PostLike
from Messages.models import Message
from Messages.forms import Share

# Create your views here.

class CreatePost(LoginRequiredMixin, CreateView):
    model = Post
    fields = ('image', 'caption',)
    template_name = 'Posts/post.html'
    context_object_name = 'form'

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = self.request.user
        post.save()

        return redirect('profile:profile')


class ViewPost(DetailView):
    model = Post
    context_object_name = 'post'
    template_name = 'Posts/single-post.html'

    def comments_liked(self):
        return CommentLike.objects.filter(liker=self.request.user).values_list('comment', flat=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments_liked'] = self.comments_liked()

        return context


class EditPost(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ('caption',)
    context_object_name = 'form'
    template_name = 'Posts/post.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pk'] = self.object.pk

        return context

    def form_valid(self, form):
        form.save()
        return redirect('post:single_post', pk=self.object.pk)


class DeletePost(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'Posts/delete.html'
    
    def get_success_url(self):
        return reverse('profile:profile')


@login_required
def feed(req):
    search = req.GET.get('search', '')
    results = User.objects.filter(username__contains=search)

    interests = Follow.objects.filter(follower=req.user).values_list('following', flat=True)
    posts = Post.objects.filter(author__in=interests)
    likes = PostLike.objects.filter(liker=req.user).values_list('post', flat=True)

    return render(req, 'Posts/feed.html', context={'posts':posts, 'likes':likes, 'search':search, 'results':results, 'following':interests})


@login_required
def post_like(req, pk):
    post = Post.objects.get(pk=pk)
    liked = PostLike.objects.filter(liker=req.user, post=post)
    if liked:
        pass
    else:
        like = PostLike(liker=req.user, post=post)
        like.save()

    return HttpResponseRedirect(req.META.get('HTTP_REFERER'))


@login_required
def post_unlike(req, pk):
    post = Post.objects.get(pk=pk)
    liked = PostLike.objects.filter(liker=req.user, post=post)
    if liked:
        liked.delete()
    else:
        pass

    return HttpResponseRedirect(req.META.get('HTTP_REFERER'))


@login_required
def write_comment(req, pk):
    if req.method == 'POST':
        comment = req.POST.get('comment')
        commentor = req.user
        post = Post.objects.get(pk=pk)
        form = Comment(comment=comment, commentor=commentor, post=post)
        form.save()
    
    return HttpResponseRedirect(req.META.get('HTTP_REFERER'))


class EditComment(LoginRequiredMixin, UpdateView):
    model = Comment
    fields = ('comment',)
    context_object_name = 'form'
    template_name = 'Posts/post.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment'] = True
        context['cmt_pk'] = self.object.pk

        return context

    def get_success_url(self):
        return reverse('post:single_post' , kwargs={'pk':self.object.post.pk})


@login_required
def delete_comment(req, pk):
    comment = Comment.objects.get(pk=pk)
    post_pk = comment.post.pk
    comment.delete()

    return redirect('post:single_post', pk=post_pk)


@login_required
def comment_like(req, pk):
    comment = Comment.objects.get(pk=pk)
    liked = CommentLike.objects.filter(liker=req.user, comment=comment)
    if liked:
        pass
    else:
        like = CommentLike(liker=req.user, comment=comment)
        like.save()

    return HttpResponseRedirect(req.META.get('HTTP_REFERER'))


@login_required
def comment_unlike(req, pk):
    comment = Comment.objects.get(pk=pk)
    liked = CommentLike.objects.filter(liker=req.user, comment=comment)
    if liked:
        liked.delete()
    else:
        pass

    return HttpResponseRedirect(req.META.get('HTTP_REFERER'))


@login_required
def share_list(req, pk):
    interests = Follow.objects.filter(follower=req.user).values_list('following', flat=True)
    following = []
    for i in interests:
        following.append(User.objects.get(pk=i))

    return render(req, 'Posts/share.html', context={'pk':pk, 'following':following})


@login_required
def share(req, pk):
    if req.method == 'POST':
        post_pk = req.POST.get('post')
        post = Post.objects.get(pk=post_pk)
        share = Message(attachment=post)
        share.sender = req.user
        share.receiver = User.objects.get(pk=pk)
        share.save()

    return HttpResponseRedirect(req.META['HTTP_REFERER'])

templates/Posts/delete.html
{% extends 'base.html' %}

{% block body %}

<div class="col-sm-6 offset-sm-3">
    <form method="POST">
        {% csrf_token %}
        <p>Are You Sure You Want To Delete This?</p>
        <button type="submit" class="btn btn-danger btn-sm">Delete</button>
    </form>
</div>

{% endblock %}

templates/Posts/feed.html
{% extends 'base.html' %}
{% load custom_filter %}

{% block body %}

    <div class="row">
        
        {% if search %}
        
        <div class="offset-sm-3 col-sm-6 row">
            <p>Search Results For "{{search}}"</p>
    
            {% for profile in results %}
            <div class="col-sm-8">
                <a style="text-decoration: none;" href="{% url 'profile:user_profile' pk=profile.pk %}">
                    <img class="rounded-circle" src="/media/{{ profile.profile.pro_pic }}" width="40px" height="40px">
                    <span style="font-size: 18px;">{{profile.username}}</span>
                </a>
            </div>

            <div class="col-sm-4">
                {% if user != profile %}
                {% if profile.pk in following %}
                <a href="{% url 'profile:unfollow' pk=profile.pk %}" class="btn btn-primary btn-sm" style="margin-top: -8px;">Unfollow</a>
                {% else %}
                <a href="{% url 'profile:follow' pk=profile.pk %}" class="btn btn-primary btn-sm" style="margin-top: -8px;">Follow</a>
                {% endif %}
                {% endif %}
            </div>
            <br>
            <br>
            <hr>
            <br>

            {% endfor %}
        </div>
        

        {% else %}

        <div class="col-sm-8 offset-sm-2">

            {% for post in posts %}
            <h3>
                <a href="{% url 'profile:user_profile' pk=post.author.pk %}" style="text-decoration: none; color: #000;">{{post.author}}</a>
            </h3>
            <p>{{post.post_date}}</p>
            <a href="{% url 'post:single_post' pk=post.pk %}">
                <img src="/media/{{post.image}}" alt="" width="100%">
            </a>
            <p>{{post.caption}}</p>
            
            {% if user.is_authenticated %}
            {% if post.pk in likes %}
            <a href="{% url 'post:post_unlike' pk=post.pk %}"><i class="fas fa-heart"></i></a>
            {% else %}
            <a href="{% url 'post:post_like' pk=post.pk %}"><i class="far fa-heart"></i></a>
            {% endif %}
            {% endif %}

                {% if post.likes.count == 1 %}
                <span><a style="text-decoration: none;" href="{% url 'profile:post_likers' pk=post.pk %}">{{ post.likes.count }} like</a></span>
                {% elif post.likes.count > 1 %}
                <span><a style="text-decoration: none;" href="{% url 'profile:post_likers' pk=post.pk %}">{{ post.likes.count }} likes</a></span>
                {% else %}
                <span>No Likes.</span>
                {% endif %}

                &nbsp; &nbsp; {{post.comments.count}} comments
                
                &nbsp; &nbsp; <a href="{% url 'post:share_list' pk=post.pk %}"><i class="far fa-paper-plane"></i></a>

            <hr>
            {% endfor %}

        </div>
            
        {% endif %}
    </div>

{% endblock %}

templates/Posts/post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}

<center>
    <div class="col-sm-6">
        <form method="POST" enctype="multipart/form-data">
            {{ form|crispy }}
            {% csrf_token %}

            <button type="submit" class="btn btn-primary btn-sm" style="width: 100%;">{% if comment %}Update Comment{% else %}Post{% endif %}</button>
            {% if pk %}
            <a href="{% url 'post:delete_post' pk=pk %}">Delete Post</a>
            {% elif comment %}
            <a href="{% url 'post:delete_comment' pk=cmt_pk %}">Delete Comment</a>
            {% endif %}
        </form>
    </div>
</center>

{% endblock %}

templates/Posts/share.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}

    <div class=" offset-sm-4 col-sm-4">
        {% for f in following %}
        <div class="row" style="padding: 0px 0px;">
            <div class="col-sm-1">
                <img class="rounded-circle" src="/media/{{f.profile.pro_pic}}" alt="" width="40px" height="40px">
            </div>
            <div class="col-sm-8" style="padding-left: 40px;">
                <h6 style="display: inline-block;"><a href="{% url 'profile:user_profile' pk=f.pk %}">{{f.username}}</a></h6>
            </div>
            <div class="col-sm-3">
                <form method="POST" action="{% url 'post:share' pk=f.pk %}">
                    <input type="number" name="post" id="" value="{{pk}}" hidden>
                    {% csrf_token %}
        
                    <input class="btn btn-sm btn-primary" type="submit" name="" id="" value="Send">
                </form>
            </div>
        </div>

        <hr>
        
        {% endfor %}
    </div>

{% endblock %}

templates/Posts/single-post.html
{% extends 'base.html' %}
{% load custom_filter %}

{% block body %}

    <div class="row">
        <div class="offset-sm-2 col-sm-8">
            <!-- <p>{{comments_liked}} likes</p> -->
            <div class="row">
                <div class="col-sm-1">
                    <img class="rounded-circle" src="/media/{{post.author.profile.pro_pic}}" alt="" width="70px" height="70px">
                </div>
                <div class="col-sm-10" style="padding-left: 40px;">
                    <h5 style="display: inline-block;"><a href="{% url 'profile:user_profile' pk=post.author.pk %}">{{post.author.username}}</a></h5>
                    <p>{{post.post_date}}</p>
                </div>
                <div class="col-sm-1">
                    {% if post.author == user %}
                    <a href="{% url 'post:edit_post' pk=post.pk %}" class="btn btn-light btn-sm" style="margin-top: -6px;">Edit</a>
                    {% endif %}
                </div>
            </div>

            <p>{{post.caption}}</p>
            <img src="/media/{{post.image}}" alt="" width="100%">
            <hr>

            {% if user.is_authenticated %}
            {% if user.pk in post|post_liker %}
            <a href="{% url 'post:post_unlike' pk=post.pk %}"><i class="fas fa-heart"></i></a>
            {% else %}
            <a href="{% url 'post:post_like' pk=post.pk %}"><i class="far fa-heart"></i></a>
            {% endif %}
            {% endif %}
            
            {% if post.likes.count == 1 %}
            <span><a style="text-decoration: none;" href="{% url 'profile:post_likers' pk=post.pk %}">{{ post.likes.count }} like</a></span>
            {% elif post.likes.count > 1 %}
            <span><a style="text-decoration: none;" href="{% url 'profile:post_likers' pk=post.pk %}">{{ post.likes.count }} likes</a></span>
            {% else %}
            <span>No Likes.</span>
            {% endif %}
            
            {% if user.is_authenticated %}
            <a style="margin-left: 30px;" href="{% url 'post:share_list' pk=post.pk %}"><i class="far fa-paper-plane"></i></a>
            {% endif %}

            <hr>
            
            {% if post.comments.count > 0 %}
            <p>{{post.comments.count}} Comments</p>
            {% else %}
            <p>No Comments</p>
            {% endif %}
            
            {% if user.is_authenticated %}
            <form method="POST" action="{% url 'post:comment' pk=post.pk %}">
                <input type="text" class="form-control" placeholder="Write a comment.." name="comment">
                {% csrf_token %}
                
                <button style="width: 100%;" type="submit" class="btn btn-primary btn-sm">Comment</button>
            </form>
            {% endif %}
            
            <br>
            <hr>
            <br>
            
            {% for comment in post.comments.all %}
            <div class="row">
                <div class="col-sm-10">
                    <img class="rounded-circle" src="/media/{{comment.commentor.profile.pro_pic}}" alt="" width="50px" height="50px">
                    <a style="text-decoration: none;" href="{% url 'profile:user_profile' pk=comment.commentor.pk %}"><span style="font-size: larger; font-weight: 500; margin-right: 30px;">{{comment.commentor}}</span></a>
                    <span>{{comment.comment}}</span>
                </div>
                <div class="col-sm-2">
                    {% if user == comment.commentor %}
                    <a href="{% url 'post:edit_comment' pk=comment.pk %}" class="btn btn-light btn-sm">Edit</a>
                    <a href="{% url 'post:delete_comment' pk=comment.pk %}" class="btn btn-light btn-sm">Delete</a>
                    {% elif user == post.author %}
                    <a href="{% url 'post:delete_comment' pk=comment.pk %}" class="btn btn-light btn-sm">Delete</a>
                    {% endif %}
                </div>
            </div>
            
            {% if user.is_authenticated %}
            {% if comment.pk in comments_liked %}
            <a href="{% url 'post:comment_unlike' pk=comment.pk %}"><i class="fas fa-heart"></i></a>
            {% else %}
            <a href="{% url 'post:comment_like' pk=comment.pk %}"><i class="far fa-heart"></i></a>
            {% endif %}
            {% endif %}
            
            {% if comment.likes.count == 1 %}
            <span><a style="text-decoration: none;" href="{% url 'profile:comment_likers' pk=comment.pk %}">{{ comment.likes.count }} like</a></span>
            {% elif comment.likes.count > 1 %}
            <span><a style="text-decoration: none;" href="{% url 'profile:comment_likers' pk=comment.pk %}">{{ comment.likes.count }} likes</a></span>
            {% else %}
            <span>No Likes.</span>
            {% endif %}
            
            {% endfor %}
        
        </div>
    </div>

{% endblock %}