DjangoSocialMedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Posts.urls')),
    path('profile/', include('Profile.urls')),
    path('account/', include('Login.urls')),
    path('messages/', include('Messages.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Login/urls.py
from django.urls import path
from . import views


app_name = 'account'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile-setup/', views.setup_profile, name='setup_profile'),
]

Messages/urls.py
from django.urls import path
from . import views



app_name = 'messages'

urlpatterns = [
    path('', views.deport, name='deport'),
    path('<username>/', views.inbox, name='inbox'),
    path('send-message/<pk>/', views.send_message, name='send_message'),
    path('send-picture/<pk>/', views.send_picture, name='send_picture'),
    ]

Posts/urls.py
from django.urls import path
from .views import CreatePost, DeletePost, EditComment, EditPost, ViewPost, comment_like, comment_unlike, delete_comment, feed, post_like, post_unlike, share, share_list, write_comment


app_name = 'post'

urlpatterns = [
    path('', feed, name='feed'),
    path('post/', CreatePost.as_view(), name='create_post'),
    path('post/<pk>/', ViewPost.as_view(), name='single_post'),
    path('edit-post/<pk>/', EditPost.as_view(), name='edit_post'),
    path('delete-post/<pk>/', DeletePost.as_view(), name='delete_post'),
    path('like-post/<int:pk>/', post_like, name='post_like'),
    path('unlike-post/<int:pk>/', post_unlike, name='post_unlike'),
    path('comment/<int:pk>/', write_comment, name='comment'),
    path('edit-comment/<int:pk>/', EditComment.as_view(), name='edit_comment'),
    path('delete-comment/<int:pk>/', delete_comment, name='delete_comment'),
    path('like-comment/<int:pk>/', comment_like, name='comment_like'),
    path('unlike-comment/<int:pk>/', comment_unlike, name='comment_unlike'),
    path('share-post/<pk>/', share_list, name='share_list'),
    path('share/<pk>/', share, name='share'),
]

Profile/urls.py
from django.urls import path
from . import views


app_name = 'profile'

urlpatterns = [
    path('', views.profile, name='profile'),
    path('change-password/', views.change_pass, name='change_pass'),
    path('update-user-info/', views.update_profile, name='update_user'),
    path('<pk>/', views.OtherUserProfile.as_view(), name='user_profile'),
    path('change-profile-picture/<pk>/', views.UpdatePfp.as_view(), name='update_pfp'),
    path('follow/<int:pk>/', views.follow, name='follow'),
    path('unfollow/<int:pk>/', views.unfollow, name='unfollow'),
    path('check-notification/<int:pk>/', views.check_notification, name='check_notification'),
    path('followers/<int:pk>/', views.follower_list, name='followers'),
    path('following/<int:pk>/', views.following_list, name='following'),
    path('post-likes/<int:pk>/', views.post_likers, name='post_likers'),
    path('comment-likes/<int:pk>/', views.comment_likers, name='comment_likers'),
]

templates/base.html
{% load custom_filter %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <title>{% block title %}Home{% endblock %}</title>
</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'post:feed' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'profile:profile' %}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'post:create_post' %}">Create Post</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Notifications
                            {% if user.notifications|unread_count > 0 %}
                            <span style="background: red; color: #fff; border-radius: 50%; padding: 0 5px 0 5px;">{{user.notifications|unread_count}}</span>
                            {% endif %}
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" style="width: 500px; overflow: hidden;">
                            {% for notif in user.notifications.all|slice:":10" %}
                            <li {% if notif.unread %} style=" background: rgb(212, 219, 224); " {% endif %}>
                                <a class="dropdown-item" href="{% url 'profile:check_notification' pk=notif.pk %}">{{notif}}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'messages:deport' %}">
                            Messages
                            {% if user.received_from|alert %}
                            <span style="color: red;">•</span>
                            {% endif %}
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink-2" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Action
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink-2">
                            <li>
                                <a class="dropdown-item" href="{% url 'profile:update_user' %}">Update Profile</a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'profile:change_pass' %}">Change Password</a>
                            </li>
                            <hr>
                            <li>
                                <a class="dropdown-item" href="{% url 'account:logout' %}">LogOut</a>
                            </li>
                        </ul>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:login' %}">LogIn</a>
                    </li>
                    {% endif %}
                </ul>
                <form class="form-inline" action="{% url 'post:feed' %}" method="GET">
                    <div class="row">
                        <div class="col-sm-8">
                            <input class="form-control" type="search" name="search" placeholder="Search @username" aria-label="Search">
                        </div>
                        <div class="col-sm-4">
                            <button class="btn btn-outline-dark" type="submit">Search</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </nav>

    <div class="container" style="margin-top: 40px;">
        {% block body %}
        {% endblock %}
    </div>
    
</body>
</html>

templates/core.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>{% block title %}Home{% endblock %}</title>
</head>
<body>

    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html>