DjangoSocialMedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Posts.urls')),
    path('profile/', include('Profile.urls')),
    path('account/', include('Login.urls')),
    path('messages/', include('Messages.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Login/urls.py
from django.urls import path
from . import views


app_name = 'account'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile-setup/', views.setup_profile, name='setup_profile'),
]

Messages/urls.py
from django.urls import path
from . import views



app_name = 'messages'

urlpatterns = [
    path('', views.deport, name='deport'),
    path('<username>/', views.inbox, name='inbox'),
    path('send-message/<pk>/', views.send_message, name='send_message'),
    path('send-picture/<pk>/', views.send_picture, name='send_picture'),
    ]

Posts/urls.py
from django.urls import path
from .views import CreatePost, DeletePost, EditComment, EditPost, ViewPost, comment_like, comment_unlike, delete_comment, feed, post_like, post_unlike, share, share_list, write_comment


app_name = 'post'

urlpatterns = [
    path('', feed, name='feed'),
    path('post/', CreatePost.as_view(), name='create_post'),
    path('post/<pk>/', ViewPost.as_view(), name='single_post'),
    path('edit-post/<pk>/', EditPost.as_view(), name='edit_post'),
    path('delete-post/<pk>/', DeletePost.as_view(), name='delete_post'),
    path('like-post/<int:pk>/', post_like, name='post_like'),
    path('unlike-post/<int:pk>/', post_unlike, name='post_unlike'),
    path('comment/<int:pk>/', write_comment, name='comment'),
    path('edit-comment/<int:pk>/', EditComment.as_view(), name='edit_comment'),
    path('delete-comment/<int:pk>/', delete_comment, name='delete_comment'),
    path('like-comment/<int:pk>/', comment_like, name='comment_like'),
    path('unlike-comment/<int:pk>/', comment_unlike, name='comment_unlike'),
    path('share-post/<pk>/', share_list, name='share_list'),
    path('share/<pk>/', share, name='share'),
]

Profile/urls.py
from django.urls import path
from . import views


app_name = 'profile'

urlpatterns = [
    path('', views.profile, name='profile'),
    path('change-password/', views.change_pass, name='change_pass'),
    path('update-user-info/', views.update_profile, name='update_user'),
    path('<pk>/', views.OtherUserProfile.as_view(), name='user_profile'),
    path('change-profile-picture/<pk>/', views.UpdatePfp.as_view(), name='update_pfp'),
    path('follow/<int:pk>/', views.follow, name='follow'),
    path('unfollow/<int:pk>/', views.unfollow, name='unfollow'),
    path('check-notification/<int:pk>/', views.check_notification, name='check_notification'),
    path('followers/<int:pk>/', views.follower_list, name='followers'),
    path('following/<int:pk>/', views.following_list, name='following'),
    path('post-likes/<int:pk>/', views.post_likers, name='post_likers'),
    path('comment-likes/<int:pk>/', views.comment_likers, name='comment_likers'),
]

Messages/models.py
from django.db import models
from django.contrib.auth.models import User
from Posts.models import Post
from django.db.models.signals import post_save
from django.dispatch import receiver
from .tasks import message_alert

# Create your models here.

class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received')
    message = models.CharField(verbose_name='Type your message..', max_length=2000, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    attachment = models.ForeignKey(Post, on_delete=models.CASCADE, blank=True, null=True)
    picture = models.ImageField(upload_to='message', blank=True)
    preview = models.CharField(max_length=100, default='')

    def save(self, *args, **kwargs):
        if self.message != '':
            self.preview = self.message[:50]
        elif self.attachment is not None:
            self.preview = f'sent an attachment.'
        else:
            self.preview = f'sent a media.'

        return super().save(*args, **kwargs)

    class Meta:
        ordering = ('date',)


class InboxAlert(models.Model):
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_from')
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_to')
    alert = models.BooleanField(default=True)
    last_alert = models.DateTimeField(auto_now=True)
    message = models.CharField(max_length=100, default='')

    class Meta:
        ordering = ('-last_alert',)


@receiver(post_save, sender=Message)
def msg_alert(sender, instance, **kwargs):
    message_alert.delay(instance.sender.pk, instance.receiver.pk, instance.preview)

Messages/forms.py
from django.db.models.fields import IntegerField
from django.forms import ModelForm
from django.forms.fields import CharField, ImageField
from django.forms.widgets import HiddenInput
from .models import Message


class SendMessage(ModelForm):
    message = CharField(required=True)
    class Meta:
        model = Message
        fields = ('message',)


class SendPicture(ModelForm):
    picture = ImageField(required=True)
    class Meta:
        model = Message
        fields = ('picture',)


class Share(ModelForm):
    attachment = IntegerField(HiddenInput(attrs={'hidden':True}))
    class Meta:
        model = Message
        fields = ('attachment',)

Messages/views.py
from django.http.response import HttpResponseRedirect
from Posts.templatetags.custom_filter import alert
from django.dispatch.dispatcher import receiver
from django.shortcuts import render
from django.contrib.auth.models import User
from .forms import SendMessage, SendPicture
from .models import Message, InboxAlert

# Create your views here.

def deport(req):
    return render(req, template_name='Messages/deport.html', context={})


def inbox(req, username):
    recipient = User.objects.get(username=username)
    new_message = SendMessage()
    new_picture = SendPicture()
    
    messages = Message.objects.filter(sender__in=[req.user, recipient], receiver__in=[req.user, recipient])

    InboxAlert.objects.filter(sender=recipient, receiver=req.user).update(alert=False)

    return render(req, template_name='Messages/inbox.html', context={'recipient':recipient, 'new_message':new_message, 'new_picture':new_picture, 'messages':messages})


def send_message(req, pk):
    recipient = User.objects.get(pk=pk)

    if req.method == 'POST':
        message = req.POST.get('message')
        if message != '':
            form = Message(message=message)
            form.sender = req.user
            form.receiver = recipient
            form.save()
    
    return HttpResponseRedirect(req.META['HTTP_REFERER'])


def send_picture(req, pk):
    recipient = User.objects.get(pk=pk)

    if req.method == 'POST':
        picture = req.FILES.get('picture')
        if picture is not None:
            form = Message(picture=picture)
            form.sender = req.user
            form.receiver = recipient
            form.save()
    
    return HttpResponseRedirect(req.META['HTTP_REFERER'])

templates/Messages/deport.html
{% extends 'base.html' %}

{% block body %}

    <div class="row">
        <div class="offset-sm-3 col-sm-6">
            <h3 style="margin-bottom: 40px;">Messages</h3>
            {% for inbox in user.received_from.all %}
                <a style="text-decoration: none; color: #000;" href="{% url 'messages:inbox' username=inbox.sender %}"><h6 style="background-color: rgb(241, 241, 241);">{{inbox.sender}}
                    {% if inbox.alert %}
                    <span style="color: red;">•</span>
                    {% endif %}
                </h6></a>
                <p style="padding-left: 20px; margin-top: -5px;">{{inbox.message}}</p>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/Messages/inbox.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}

    {% if alert %}
        <div class="alert-warning">{{alert}}</div>
    {% endif %}

    <div class="row">
        <div class="col-sm-3">
            {% for inbox in user.received_from.all %}
            <a style="text-decoration: none; color: #000;" href="{% url 'messages:inbox' username=inbox.sender %}"><p style="background-color: rgb(241, 241, 241);">{{inbox.sender}}
                {% if inbox.alert %}
                <span style="color: red;">•</span>
                {% endif %}
            </p></a>
            <p></p>
        {% endfor %}
        </div>
        <div class="col-sm-6">
            <div class="row" style="padding: 20px; border-bottom: 1px solid rgb(190, 190, 190);">
                <div class="col-sm-1">
                    <a href="{% url 'profile:user_profile' pk=recipient.pk %}"><img class="rounded-circle" src="/media/{{recipient.profile.pro_pic}}" alt="" width="50px" height="50px"></a>
                </div>
                <div class="col-sm-10" style="padding-left: 25px; padding-top: 7px;">
                    <h4 style="display: inline-block;"><a style="text-decoration: none; color: #000;" href="{% url 'profile:user_profile' pk=recipient.pk %}">{{recipient}}</a></h4>
                </div>
            </div>
            <div style="height: 77vh; overflow-y: scroll; background-color: #dbdbdb; padding: 20px;">
                {% for message in messages %}
                
                {% if message.sender == user %}
                <div>
                    
                    {% if message.message != '' %}
                    <div class="d-flex flex-row-reverse">
                        <p style="display: inline-block; background: #8f91ef; padding: 7px 20px; overflow: hidden; border-radius: 30px; max-width: 75%;">{{ message.message }}</p>
                    </div>

                    {% elif message.picture %}
                    <div class="d-flex flex-row-reverse">
                        <img src="/media/{{ message.picture }}" alt="" width="80%">
                    </div>
                    
                    {% elif message.attachment %}
                    <div class="d-flex flex-row-reverse">
                        <div style="background: #8f91ef; overflow: hidden; border-radius: 30px; width: 75%;">
                            <a href="{% url 'post:single_post' pk=message.attachment.pk %}">
                                <p style="padding: 7px 20px 0 20px; text-decoration: none; color: #000;">(@{{message.attachment.author}}) {{message.attachment.caption|slice:":50"}}</p>
                                <img src="/media/{{message.attachment.image}}" alt="" width="100%">
                            </a>
                        </div>
                    </div>
                    {% endif %}
                </div>

                {% else %}
                <div>

                    {% if message.message != '' %}
                    <div>
                        <p style="display: inline-block; background: #fff; padding: 7px 20px; overflow: hidden; border-radius: 30px; max-width: 75%;">{{ message.message }}</p>
                    </div>
                   
                    {% elif message.picture %}
                        <img src="/media/{{ message.picture }}" alt="" width="80%"">
                   
                    {% elif message.attachment %}
                        <div style="background: #fff; overflow: hidden; border-radius: 30px; width: 75%;">
                            <a href="{% url 'post:single_post' pk=message.attachment.pk %}">
                                <p style="padding: 7px 20px 0 20px; text-decoration: none; color: #000;">(@{{message.attachment.author}}) {{message.attachment.caption|slice:":50"}}</p>
                                <img src="/media/{{message.attachment.image}}" alt="" width="100%">
                            </a>
                        </div>
                    {% endif %}
                </div>

                {% endif %}
                <br>

                {% endfor %}
            </div>
            <div>
                <form method="POST" action="{% url 'messages:send_message' pk=recipient.pk %}">
                    {{ new_message|crispy }}
                    {% csrf_token %}
                    <input type="submit" value="SEND" class="btn btn-sm btn-primary">
                </form>
                <br>
                <form method="POST" enctype="multipart/form-data" action="{% url 'messages:send_picture' pk=recipient.pk %}">
                    {{ new_picture|crispy }}
                    {% csrf_token %}
                    <input type="submit" value="SEND" class="btn btn-sm btn-primary">
                </form>
                <br>
                <br>
                <br>
            </div>
        </div>
    </div>

{% endblock %}